platform :ios, '9.0'
use_frameworks!

target 'FireTVKit_Example' do
  pod 'FireTVKit', :path => '../'

  target 'FireTVKit_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 7.3'
    pod 'Quick', '~> 1.3'
  end
end

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
