use_frameworks!

target 'FireTVKit_Example' do
  pod 'FireTVKit', :path => '../'

  target 'FireTVKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
